#!/bin/sh
# disasm_plus

# The intention of the --trace-to line, here, is to produce
# a disassembly trace of exactly the instructions that were fed in
# via the "input" file (those beginning at $300).
$BOBBIN -m plus --simple --die-on-brk --trace-to 76466:195 < input \
    2>&1 | sed 's/^.*bobbin:/bobbin:/'
echo '--------------------'
echo ' TRACE:'
echo '--------------------'
cat trace.log
