#!/bin/sh

cat > ./reverse <<EOF
#!$BOBBIN --run-basic
#
# Extra comment lines

10 INPUT "";A$
20 AL=LEN(A$)
30 FOR I=1 TO AL
40 PRINT MID\$(A$,AL-(I-1),1);
50 NEXT
60 END
EOF
chmod +x ./reverse

echo Hello | ./reverse | sed -e 's/^/-= /' -e 's/$/ =-/'
