#!/bin/sh
# disasm_enhanced_iie

$BOBBIN --simple --die-on-brk --trace-to 95013 < input \
    2>&1 | sed 's/^.*bobbin:/bobbin:/'
echo '--------------------'
echo ' TRACE:'
echo '--------------------'
cat trace.log
