#!/bin/sh

rm -f testdisk.nib
cp indisk.nib testdisk.nib

$BOBBIN -m plus --disk testdisk.nib <<EOF
10 FOR I=1 TO 10
20 ? SPC(I);"BOBBIN RULES!"
30 NEXT I
CATALOG
INIT RUN
EOF

echo '+++++'

$BOBBIN -m plus --disk testdisk.nib <<EOF
CATALOG
EOF
